// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Q.A.__social_network.Data;

#nullable disable

namespace Q.A.__social_network.Migrations
{
    [DbContext(typeof(Social_NetworkContext))]
    [Migration("20221015002006_Version5")]
    partial class Version5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Q.A.__social_network.Models.UserModel", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Q.A.__social_network.Models.UserModel", b =>
                {
                    b.OwnsMany("Q.A.__social_network.Models.QuestionModel", "Questions", b1 =>
                        {
                            b1.Property<int>("IdQuestion")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("IdUser")
                                .HasColumnType("int");

                            b1.Property<string>("Question")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int?>("UserIdUser")
                                .HasColumnType("int");

                            b1.Property<int>("UserModelIdUser")
                                .HasColumnType("int");

                            b1.HasKey("IdQuestion");

                            b1.HasIndex("IdUser");

                            b1.HasIndex("UserIdUser");

                            b1.ToTable("Questions");

                            b1.WithOwner()
                                .HasForeignKey("IdUser");

                            b1.HasOne("Q.A.__social_network.Models.UserModel", "User")
                                .WithMany()
                                .HasForeignKey("UserIdUser");

                            b1.Navigation("User");
                        });

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
